# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c81ae83a1948d1fbd70fd9153f536fa0b654b6a31df674c6010ccb60b65a43880143cb278b0df09830cee65addb118e622e7880b598f568d0d512cf8706160f

test:
  secret_key_base: 7610e3c25c639c04ae1be299446e23c40b436ac896a6440e29d15e9dc02e2151d13e91c19e4eef5b29797550aa4d6e0b05a2b7175145f48b495c631b3d942c84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
